import { expect, test } from "bun:test";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

test("dir plus --preset nest writes files without opening the TUI", async () => {
  const parent = await mkdtemp(join(tmpdir(), "cga-preset-"));
  const dest = join(parent, "nest-smoke");
  const cli = join(import.meta.dir, "../src/index.ts");
  const proc = Bun.spawn(
    [
      process.execPath,
      cli,
      dest,
      "--preset",
      "nest",
      "--no-install",
      "--no-git",
    ],
    { stdout: "pipe", stderr: "pipe" },
  );
  const hung = new Promise<never>((_, reject) => {
    setTimeout(() => {
      proc.kill();
      reject(new Error("CLI hung; TUI likely opened"));
    }, 20000);
  });
  try {
    const code = await Promise.race([proc.exited, hung]);
    const stdout = await new Response(proc.stdout).text();
    const stderr = await new Response(proc.stderr).text();
    expect(code).toBe(0);
    expect(stderr).toBe("");
    expect(stdout).toContain("done:");
    expect(stdout).toContain(dest);
    const readme = await readFile(join(dest, "README.md"), "utf8");
    expect(readme).toBe("# nest-smoke\n\nGenerated by create-gb-app.\n");
    const pkg = await readFile(join(dest, "package.json"), "utf8");
    expect(pkg).toContain("turbo");
  } finally {
    await rm(parent, { recursive: true, force: true });
  }
});
