export const SHADCN_FOUNDATION = {
  preset: 'b1YnQPagE',
  cliVersion: '4.21.0',
  base: 'base',
  style: 'nova',
  baseColor: 'zinc',
  theme: 'zinc',
  chartColor: 'blue',
  iconLibrary: 'lucide',
  font: 'geist',
  fontHeading: 'inherit',
  radius: 'small',
  components: [
    'button',
    'card',
    'checkbox',
    'field',
    'input',
    'label',
    'select',
    'separator',
    'textarea',
  ],
} as const;
