import { expect, test } from 'bun:test';

import { setFileIfAbsent } from '#/generate/files';

test('setFileIfAbsent writes when the path is missing', () => {
  const files: Record<string, string> = {};
  setFileIfAbsent(files, 'README.md', '# stub\n');
  expect(files['README.md']).toBe('# stub\n');
});

test('setFileIfAbsent keeps a richer README', () => {
  const files = { 'README.md': '# nest-app\n\nInstall pnpm and run turbo.\n' };
  setFileIfAbsent(
    files,
    'README.md',
    '# nest-app\n\nGenerated by create-gb-app.\n'
  );
  expect(files['README.md']).toBe(
    '# nest-app\n\nInstall pnpm and run turbo.\n'
  );
});
