import type { Stack } from '#/types/stack';

import type {
  FileMap,
  GenerateContext,
  PackageJsonShape,
} from '../types/generate';
import { PACKAGE_MANAGER_METADATA } from './package-managers';

const LABELS: Record<string, string> = {
  next: 'Next.js',
  'tanstack-start': 'TanStack Start',
  self: 'Fullstack application',
  nest: 'Nest',
  hono: 'Hono',
  convex: 'Convex',
  orpc: 'oRPC',
  trpc: 'tRPC',
  postgres: 'PostgreSQL',
  sqlite: 'SQLite',
  mysql: 'MySQL',
  prisma: 'Prisma',
  drizzle: 'Drizzle',
  'better-auth': 'Better Auth',
  clerk: 'Clerk',
  stripe: 'Stripe',
  polar: 'Polar',
  eslint: 'ESLint',
  oxlint: 'Oxlint',
  'react-hook-form': 'React Hook Form',
  'tanstack-form': 'TanStack Form',
};

const FEATURE_DESCRIPTIONS: Record<string, string> = {
  next: 'React framework for the web',
  'tanstack-start': 'Fullstack React framework',
  self: 'Frontend and server in one application',
  nest: 'Application server',
  hono: 'Lightweight API server',
  convex: 'Reactive backend and database',
  orpc: 'Typesafe API layer',
  trpc: 'Typesafe API layer',
  postgres: 'Relational database',
  sqlite: 'Embedded database',
  mysql: 'Relational database',
  prisma: 'Database schema and client',
  drizzle: 'Database schema and queries',
  'better-auth': 'Authentication',
  clerk: 'Authentication',
  stripe: 'Payments',
  polar: 'Payments',
  eslint: 'Code linting',
  oxlint: 'Code linting',
  'react-hook-form': 'Form state and validation',
  'tanstack-form': 'Form state and validation',
  turborepo: 'Shared workspace tasks',
};

const SCRIPT_DESCRIPTIONS: Record<string, string> = {
  dev: 'Start the development server',
  build: 'Build the project for production',
  start: 'Start the production build',
  lint: 'Check the code',
  'db:generate': 'Generate database client or migration files',
  'db:push': 'Apply the schema to the database',
  'db:migrate': 'Run database migrations',
  'convex:dev': 'Connect and run the Convex development backend',
  'convex:codegen': 'Regenerate Convex types',
};

function features(stack: Stack): string[] {
  const selected: string[] = [stack.frontend, stack.backend];
  if ('api' in stack && stack.api !== 'none') selected.push(stack.api);
  if ('database' in stack && stack.database !== 'none') {
    selected.push(stack.database, stack.orm);
  }
  if (stack.auth !== 'none') selected.push(stack.auth);
  if (stack.payments !== 'none') selected.push(stack.payments);
  if (stack.form !== 'none') selected.push(stack.form);
  if (stack.structure === 'turborepo') selected.push('turborepo');
  selected.push(stack.linter);
  return selected.map(
    (item) =>
      `- **${LABELS[item] ?? item}** — ${FEATURE_DESCRIPTIONS[item] ?? 'Included in the stack'}`
  );
}

function existingNotes(readme: string | undefined): string {
  if (!readme) return '';
  const body = readme
    .replace(/^# [^\n]*\n/, '')
    .replace(/^\s*Generated by create-gb-app\.\s*/, '')
    .trim();
  if (!body) return '';
  return body.startsWith('## ') ? body : `## Configuration notes\n\n${body}`;
}

function databaseSetup(
  stack: Stack,
  files: FileMap,
  scripts: Record<string, string>,
  run: string
): string {
  if (!('database' in stack) || stack.database === 'none') return '';
  const envPath = Object.keys(files).find((path) => path.endsWith('.env'));
  const commands = ['db:generate', 'db:push', 'db:migrate']
    .filter((name) => name in scripts)
    .map((name) => `${run} ${name}`);
  return [
    '## Database setup',
    '',
    `Set the database connection in \`${envPath ?? '.env'}\` before running schema commands.`,
    '',
    ...(commands.length ? ['```bash', ...commands, '```'] : []),
  ].join('\n');
}

export function generateReadme(
  stack: Stack,
  ctx: GenerateContext,
  files: FileMap,
  pkg: PackageJsonShape
): string {
  const manager = PACKAGE_MANAGER_METADATA[ctx.packageManager];
  const notes = existingNotes(files['README.md']);
  const hasDatabaseNotes = /^## Database setup\b/im.test(notes);
  const envPaths = Object.keys(files).filter((path) =>
    /(^|\/)\.env(\.example|\.local)?$/.test(path)
  );
  const scripts = Object.keys(pkg.scripts).map((name) => {
    const description = SCRIPT_DESCRIPTIONS[name] ?? 'Run the project task';
    return `- \`${manager.run} ${name}\` — ${description}.`;
  });
  const sections = [
    `# ${ctx.projectName}`,
    'Created with create-gb-app, a TypeScript starter configured for this stack.',
    `## Features\n\n${features(stack).join('\n')}`,
    `## Getting started\n\nInstall dependencies from the project root:\n\n\`\`\`bash\n${manager.install}\n\`\`\``,
  ];

  if (!hasDatabaseNotes) {
    const setup = databaseSetup(stack, files, pkg.scripts, manager.run);
    if (setup) sections.push(setup);
  }
  if (notes) sections.push(notes);

  if (stack.backend === 'convex' && pkg.scripts['convex:dev']) {
    sections.push(
      `## Start developing\n\nConnect Convex in one terminal with \`${manager.run} convex:dev\`, then run \`${manager.run} dev\` in another.`
    );
  } else {
    sections.push(
      `## Start developing\n\n\`\`\`bash\n${manager.run} dev\n\`\`\``
    );
  }

  if (envPaths.length > 0) {
    sections.push(
      `## Environment configuration\n\nReview the generated ${envPaths.map((path) => `\`${path}\``).join(', ')} file${envPaths.length === 1 ? '' : 's'} and replace development placeholders before deployment.`
    );
  }

  sections.push(`## Available scripts\n\n${scripts.join('\n')}`);
  return `${sections.join('\n\n')}\n`;
}
