import type { HonoStack } from '#/types/stack';

import type { EmitCtx } from '../../types/generate';
import { setFile } from '../files';
import { workspaceProtocol } from '../workspace-protocol';
import { emitBiome } from './biome';
import { emitDbSetup } from './db-setup';
import { emitDrizzle } from './drizzle';
import { emitEslintPrettier } from './eslint';
import { emitOxlint } from './oxlint';
import { emitPolar } from './polar';
import { emitPostgres } from './postgres';
import { emitPrisma } from './prisma';
import { emitStripe } from './stripe';

const SERVER_URL = 'http://localhost:3333';
const WEB_ORIGIN = 'http://localhost:3000';

function proto(ctx: EmitCtx): string {
  return workspaceProtocol(ctx.packageManager);
}

export function emitHono(ctx: EmitCtx): void {
  if (ctx.stack.backend !== 'hono') {
    throw new Error('emitHono requires hono');
  }

  const stack = ctx.stack;
  const dep = proto(ctx);
  ctx.pkg.private = true;
  ctx.pkg.scripts.dev = 'turbo dev';
  ctx.pkg.scripts.build = 'turbo build';
  ctx.pkg.scripts.lint = 'turbo lint';
  ctx.pkg.devDependencies.turbo = '^2.5.6';
  ctx.pkg.devDependencies.typescript = '^5.9.2';
  ctx.pkg.workspaces = ['apps/*', 'packages/*'];

  setFile(
    ctx.files,
    'turbo.json',
    JSON.stringify(
      {
        $schema: 'https://turborepo.dev/schema.json',
        tasks: {
          build: {
            dependsOn: ['^build'],
            outputs: [
              'dist/**',
              '.next/**',
              '!.next/cache/**',
              '.output/**',
              '.vinxi/**',
            ],
          },
          dev: { cache: false, persistent: true },
          lint: { dependsOn: ['^lint'] },
        },
      },
      null,
      2
    )
  );

  setFile(
    ctx.files,
    '.gitignore',
    `node_modules
.turbo
.next
.output
.vinxi
dist
.env
*.log
`
  );

  emitTypescriptConfig(ctx);
  if (stack.database !== 'none') {
    emitPostgres(ctx);
    switch (stack.orm) {
      case 'prisma':
        emitPrisma(ctx);
        break;
      case 'drizzle':
        emitDrizzle(ctx);
        break;
      case 'none':
        throw new Error('orm none requires database none');
      default: {
        const _exhaustive: never = stack.orm;
        throw new Error(`unhandled orm: ${_exhaustive}`);
      }
    }
    emitDbSetup(ctx);
  }

  if (stack.api === 'orpc') {
    emitOrpcContract(ctx, dep);
  } else if (stack.api === 'trpc') {
    emitTrpcContract(ctx, dep);
  }

  emitUiPackage(ctx, dep);
  emitServer(ctx, stack, dep);
  emitWeb(ctx, stack, dep);
  emitChosenLinter(ctx, stack);
  emitChosenPayments(ctx, stack);

  setFile(
    ctx.files,
    'README.md',
    `# ${ctx.projectName}

Generated by create-gb-app.

The server listens with [@hono/node-server](https://hono.dev/docs/getting-started/nodejs).
See the Hono Node guide for the Node.js adapter.
`
  );
}

function emitChosenLinter(ctx: EmitCtx, stack: HonoStack): void {
  switch (stack.linter) {
    case 'eslint':
      emitEslintPrettier(ctx);
      break;
    case 'biome':
      emitBiome(ctx);
      break;
    case 'oxlint':
      emitOxlint(ctx);
      break;
    default: {
      const _exhaustive: never = stack.linter;
      throw new Error(`unhandled linter: ${_exhaustive}`);
    }
  }
}

function emitChosenPayments(ctx: EmitCtx, stack: HonoStack): void {
  switch (stack.payments) {
    case 'none':
      break;
    case 'stripe':
      emitStripe(ctx);
      break;
    case 'polar':
      emitPolar(ctx);
      break;
    default: {
      const _exhaustive: never = stack.payments;
      throw new Error(`unhandled payments: ${_exhaustive}`);
    }
  }
}

function emitTypescriptConfig(ctx: EmitCtx): void {
  setFile(
    ctx.files,
    'packages/typescript-config/package.json',
    JSON.stringify(
      {
        name: '@repo/typescript-config',
        version: '0.0.0',
        private: true,
        files: ['base.json'],
      },
      null,
      2
    )
  );
  setFile(
    ctx.files,
    'packages/typescript-config/base.json',
    JSON.stringify(
      {
        compilerOptions: {
          strict: true,
          target: 'ES2022',
          module: 'ESNext',
          moduleResolution: 'bundler',
          skipLibCheck: true,
        },
      },
      null,
      2
    )
  );
}

function emitOrpcContract(ctx: EmitCtx, dep: string): void {
  setFile(
    ctx.files,
    'packages/contract/package.json',
    JSON.stringify(
      {
        name: '@repo/contract',
        version: '0.0.0',
        private: true,
        type: 'module',
        exports: { '.': './src/index.ts' },
        dependencies: {
          '@orpc/contract': 'beta',
          '@orpc/openapi': 'beta',
          zod: '^4.1.5',
        },
        devDependencies: {
          '@repo/typescript-config': dep,
        },
      },
      null,
      2
    )
  );
  setFile(
    ctx.files,
    'packages/contract/src/index.ts',
    `export { contract } from "./contract";
`
  );
  setFile(
    ctx.files,
    'packages/contract/src/contract.ts',
    `import { oc } from "@orpc/contract";
import { openapi } from "@orpc/openapi";
import { z } from "zod";

const UserSchema = z.object({
  id: z.string(),
  email: z.string(),
  name: z.string(),
});

const NoteSchema = z.object({
  id: z.string(),
  title: z.string(),
  body: z.string(),
  createdAt: z.coerce.date(),
  updatedAt: z.coerce.date(),
});

export const contract = {
  me: oc
    .meta(openapi({ method: "GET", path: "/me" }))
    .output(UserSchema),
  notes: {
    list: oc
      .meta(openapi({ method: "GET", path: "/notes" }))
      .output(z.array(NoteSchema)),
    create: oc
      .meta(openapi({ method: "POST", path: "/notes" }))
      .input(z.object({ title: z.string().min(1), body: z.string() }))
      .output(NoteSchema),
    update: oc
      .meta(openapi({ method: "PATCH", path: "/notes/{id}" }))
      .input(
        z.object({
          id: z.string(),
          title: z.string().min(1),
          body: z.string(),
        }),
      )
      .output(NoteSchema),
    delete: oc
      .meta(openapi({ method: "DELETE", path: "/notes/{id}" }))
      .input(z.object({ id: z.string() }))
      .output(z.object({ ok: z.literal(true) })),
  },
};
`
  );
}

function emitTrpcContract(ctx: EmitCtx, dep: string): void {
  setFile(
    ctx.files,
    'packages/contract/package.json',
    JSON.stringify(
      {
        name: '@repo/contract',
        version: '0.0.0',
        private: true,
        type: 'module',
        exports: { '.': './src/index.ts' },
        dependencies: {
          '@trpc/server': '^11.5.1',
          zod: '^4.1.5',
        },
        devDependencies: {
          '@repo/typescript-config': dep,
        },
      },
      null,
      2
    )
  );
  setFile(
    ctx.files,
    'packages/contract/src/index.ts',
    `import { initTRPC } from "@trpc/server";
import { z } from "zod";

export type Note = {
  id: string;
  title: string;
  body: string;
  createdAt: Date;
  updatedAt: Date;
};

export type NoteInput = { title: string; body: string };

export type NoteStore = {
  list: (userId: string | null) => Promise<Note[]>;
  create: (userId: string | null, input: NoteInput) => Promise<Note>;
  update: (
    userId: string | null,
    input: NoteInput & { id: string },
  ) => Promise<Note>;
  remove: (userId: string | null, id: string) => Promise<{ ok: true }>;
};

export type TrpcContext = {
  userId: string | null;
  notes: NoteStore;
};

const t = initTRPC.context<TrpcContext>().create();

export const appRouter = t.router({
  notes: t.router({
    list: t.procedure.query(({ ctx }) => ctx.notes.list(ctx.userId)),
    create: t.procedure
      .input(z.object({ title: z.string(), body: z.string() }))
      .mutation(({ ctx, input }) => ctx.notes.create(ctx.userId, input)),
    update: t.procedure
      .input(z.object({ id: z.string(), title: z.string(), body: z.string() }))
      .mutation(({ ctx, input }) => ctx.notes.update(ctx.userId, input)),
    remove: t.procedure
      .input(z.object({ id: z.string() }))
      .mutation(({ ctx, input }) => ctx.notes.remove(ctx.userId, input.id)),
  }),
});

export type AppRouter = typeof appRouter;
`
  );
}

function emitUiPackage(ctx: EmitCtx, dep: string): void {
  setFile(
    ctx.files,
    'packages/ui/package.json',
    JSON.stringify(
      {
        name: '@repo/ui',
        version: '0.0.0',
        private: true,
        type: 'module',
        exports: {
          './button': './src/button.tsx',
          './input': './src/input.tsx',
          './card': './src/card.tsx',
          './utils': './src/utils.ts',
        },
        dependencies: {
          clsx: '^2.1.1',
          'tailwind-merge': '^3.3.1',
          react: '^19.1.1',
        },
        devDependencies: {
          '@repo/typescript-config': dep,
          '@types/react': '^19.1.12',
        },
      },
      null,
      2
    )
  );
  setFile(
    ctx.files,
    'packages/ui/src/utils.ts',
    `import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}
`
  );
  setFile(
    ctx.files,
    'packages/ui/src/button.tsx',
    `import type { ButtonHTMLAttributes } from "react";
import { cn } from "./utils";

export function Button({
  className,
  ...props
}: ButtonHTMLAttributes<HTMLButtonElement>) {
  return (
    <button
      className={cn(
        "inline-flex h-9 items-center justify-center rounded-md bg-neutral-900 px-3 text-sm font-medium text-white disabled:opacity-50",
        className,
      )}
      {...props}
    />
  );
}
`
  );
  setFile(
    ctx.files,
    'packages/ui/src/input.tsx',
    `import type { InputHTMLAttributes } from "react";
import { cn } from "./utils";

export function Input({
  className,
  ...props
}: InputHTMLAttributes<HTMLInputElement>) {
  return (
    <input
      className={cn(
        "h-9 w-full rounded-md border border-neutral-300 bg-transparent px-3 text-sm",
        className,
      )}
      {...props}
    />
  );
}
`
  );
  setFile(
    ctx.files,
    'packages/ui/src/card.tsx',
    `import type { HTMLAttributes } from "react";
import { cn } from "./utils";

export function Card({ className, ...props }: HTMLAttributes<HTMLDivElement>) {
  return (
    <div
      className={cn("rounded-lg border border-neutral-200 bg-white p-4", className)}
      {...props}
    />
  );
}
`
  );
}

function emitServer(ctx: EmitCtx, stack: HonoStack, dep: string): void {
  const dependencies: Record<string, string> = {
    '@hono/node-server': '^2.1.1',
    hono: '^4.13.7',
  };
  const devDependencies: Record<string, string> = {
    '@repo/typescript-config': dep,
    '@types/node': '^24.3.1',
    tsx: '^4.20.5',
    typescript: '^5.9.2',
  };

  if (stack.database !== 'none' && stack.orm === 'prisma') {
    dependencies['@prisma/client'] = '^6.16.1';
    devDependencies.prisma = '^6.16.1';
  }
  if (stack.database !== 'none' && stack.orm === 'drizzle') {
    dependencies['drizzle-orm'] = '^0.44.5';
    devDependencies['drizzle-kit'] = '^0.31.4';
  }
  if (stack.auth === 'better-auth') {
    dependencies['better-auth'] = '^1.3.8';
  }
  if (stack.auth === 'clerk') {
    dependencies['@hono/clerk-auth'] = '^3.1.1';
  }
  if (stack.database !== 'none' && stack.api === 'orpc') {
    dependencies['@orpc/openapi'] = 'beta';
    dependencies['@orpc/server'] = 'beta';
    dependencies['@repo/contract'] = dep;
  }
  if (stack.database !== 'none' && stack.api === 'trpc') {
    dependencies['@hono/trpc-server'] = '^0.4.2';
    dependencies['@repo/contract'] = dep;
    dependencies['@trpc/server'] = '^11.5.1';
  }

  setFile(
    ctx.files,
    'apps/server/package.json',
    JSON.stringify(
      {
        name: 'server',
        version: '0.0.0',
        private: true,
        type: 'module',
        scripts: {
          dev: 'tsx watch src/index.ts',
          start: 'tsx src/index.ts',
          build: 'tsc',
        },
        dependencies,
        devDependencies,
      },
      null,
      2
    )
  );
  setFile(
    ctx.files,
    'apps/server/tsconfig.json',
    JSON.stringify(
      {
        extends: '@repo/typescript-config/base.json',
        compilerOptions: {
          outDir: 'dist',
          rootDir: 'src',
          types: ['node'],
        },
        include: ['src'],
      },
      null,
      2
    )
  );

  if (stack.auth === 'better-auth' && stack.database !== 'none') {
    emitServerAuth(ctx, stack);
  }
  if (stack.database !== 'none') {
    emitNotesStore(ctx, stack);
  }
  if (stack.database !== 'none' && stack.api === 'orpc') {
    emitOrpcRouter(ctx, stack);
  }

  setFile(ctx.files, 'apps/server/src/index.ts', serverEntry(stack));
}

function authProvider(stack: HonoStack): string {
  if (stack.database === 'mysql') {
    return 'mysql';
  }
  if (stack.database === 'sqlite') {
    return 'sqlite';
  }
  return 'postgresql';
}

function emitServerAuth(ctx: EmitCtx, stack: HonoStack): void {
  const provider = authProvider(stack);
  const source =
    stack.orm === 'drizzle'
      ? `import { betterAuth } from "better-auth";
import { drizzleAdapter } from "better-auth/adapters/drizzle";
import { db } from "./db";

export const auth = betterAuth({
  database: drizzleAdapter(db, { provider: "${stack.database === 'mysql' ? 'mysql' : stack.database === 'sqlite' ? 'sqlite' : 'pg'}" }),
  emailAndPassword: { enabled: true },
  trustedOrigins: ["${WEB_ORIGIN}"],
  baseURL: "${SERVER_URL}",
});
`
      : `import { betterAuth } from "better-auth";
import { prismaAdapter } from "better-auth/adapters/prisma";
import { prisma } from "./db";

export const auth = betterAuth({
  database: prismaAdapter(prisma, { provider: "${provider}" }),
  emailAndPassword: { enabled: true },
  trustedOrigins: ["${WEB_ORIGIN}"],
  baseURL: "${SERVER_URL}",
});
`;
  setFile(ctx.files, 'apps/server/src/auth.ts', source);
}

function emitNotesStore(ctx: EmitCtx, stack: HonoStack): void {
  const authed = stack.auth !== 'none';
  if (stack.orm === 'drizzle') {
    setFile(
      ctx.files,
      'apps/server/src/notes.ts',
      `import { eq } from "drizzle-orm";
import { db } from "./db";
import { notes } from "./schema";

export type Note = {
  id: string;
  title: string;
  body: string;
  createdAt: Date;
  updatedAt: Date;
};

function row(input: { id: string; title: string; body: string }): Note {
  const now = new Date();
  return { ...input, createdAt: now, updatedAt: now };
}

export async function listNotes(_userId: string | null): Promise<Note[]> {
  const found = await db.select().from(notes);
  return found.map((note) => row(note));
}

export async function createNote(
  _userId: string | null,
  input: { title: string; body: string },
): Promise<Note> {
  const created = row({
    id: crypto.randomUUID(),
    title: input.title,
    body: input.body,
  });
  await db.insert(notes).values({
    id: created.id,
    title: created.title,
    body: created.body,
  });
  return created;
}

export async function updateNote(
  _userId: string | null,
  input: { id: string; title: string; body: string },
): Promise<Note> {
  await db
    .update(notes)
    .set({ title: input.title, body: input.body })
    .where(eq(notes.id, input.id));
  return row(input);
}

export async function removeNote(
  _userId: string | null,
  id: string,
): Promise<{ ok: true }> {
  await db.delete(notes).where(eq(notes.id, id));
  return { ok: true };
}
`
    );
    return;
  }

  const scope = authed ? 'where: { userId: userId ?? "" }' : '';
  setFile(
    ctx.files,
    'apps/server/src/notes.ts',
    `import { prisma } from "./db";

export async function listNotes(userId: string | null) {
  ${authed ? 'if (!userId) {\n    return [];\n  }\n  ' : ''}return prisma.note.findMany({
    ${scope ? `${scope},` : ''}
    orderBy: { createdAt: "desc" },
  });
}

export async function createNote(
  userId: string | null,
  input: { title: string; body: string },
) {
  return prisma.note.create({
    data: {
      title: input.title,
      body: input.body,
      ${authed ? 'userId: userId ?? "",' : ''}
    },
  });
}

export async function updateNote(
  userId: string | null,
  input: { id: string; title: string; body: string },
) {
  ${authed ? 'const note = await prisma.note.findFirst({ where: { id: input.id, userId: userId ?? "" } });\n  if (!note) {\n    throw new Error("NOT_FOUND");\n  }\n  ' : ''}return prisma.note.update({
    where: { id: ${authed ? 'note.id' : 'input.id'} },
    data: { title: input.title, body: input.body },
  });
}

export async function removeNote(userId: string | null, id: string) {
  ${authed ? 'const note = await prisma.note.findFirst({ where: { id, userId: userId ?? "" } });\n  if (!note) {\n    throw new Error("NOT_FOUND");\n  }\n  await prisma.note.delete({ where: { id: note.id } });' : 'await prisma.note.delete({ where: { id } });'}
  return { ok: true as const };
}
`
  );
}

function emitOrpcRouter(ctx: EmitCtx, stack: HonoStack): void {
  const authed = stack.auth !== 'none';
  const meBody =
    stack.auth === 'better-auth'
      ? `const session = await auth.api.getSession({ headers: context.headers });
    if (!session) {
      throw new ORPCError("UNAUTHORIZED");
    }
    return session.user;`
      : authed
        ? `if (!context.userId) {
      throw new ORPCError("UNAUTHORIZED");
    }
    return { id: context.userId, email: "user@example.com", name: "User" };`
        : `return { id: "public", email: "public@example.com", name: "Public" };`;
  const guard = authed
    ? `if (!context.userId) {
      throw new ORPCError("UNAUTHORIZED");
    }
    `
    : '';
  const authImport =
    stack.auth === 'better-auth' ? `import { auth } from "./auth";\n` : '';

  setFile(
    ctx.files,
    'apps/server/src/orpc.ts',
    `import { ORPCError, implement } from "@orpc/server";
import { contract } from "@repo/contract";
${authImport}import { createNote, listNotes, removeNote, updateNote } from "./notes";

const base = implement(contract).$context<{ headers: Headers; userId: string | null }>();

export const router = base.router({
  me: base.me.handler(async ({ context }) => {
    ${meBody}
  }),
  notes: {
    list: base.notes.list.handler(async ({ context }) => {
      ${guard}return listNotes(context.userId);
    }),
    create: base.notes.create.handler(async ({ context, input }) => {
      ${guard}return createNote(context.userId, input);
    }),
    update: base.notes.update.handler(async ({ context, input }) => {
      ${guard}return updateNote(context.userId, input);
    }),
    delete: base.notes.delete.handler(async ({ context, input }) => {
      ${guard}return removeNote(context.userId, input.id);
    }),
  },
});
`
  );
}

function serverEntry(stack: HonoStack): string {
  const imports = [
    `import { serve } from "@hono/node-server";`,
    `import { Hono } from "hono";`,
    `import { cors } from "hono/cors";`,
  ];
  if (stack.auth === 'clerk') {
    imports.push(
      `import { clerkMiddleware, getAuth } from "@hono/clerk-auth";`
    );
  }
  if (stack.auth === 'better-auth' && stack.database !== 'none') {
    imports.push(`import { auth } from "./auth";`);
  }
  if (stack.database !== 'none' && stack.api === 'orpc') {
    imports.push(`import { OpenAPIHandler } from "@orpc/openapi/fetch";`);
    imports.push(`import { router } from "./orpc";`);
  }
  if (stack.database !== 'none' && stack.api === 'trpc') {
    imports.push(`import { trpcServer } from "@hono/trpc-server";`);
    imports.push(`import { appRouter } from "@repo/contract";`);
  }
  if (stack.database !== 'none' && stack.api === 'none') {
    imports.push(
      `import { createNote, listNotes, removeNote, updateNote } from "./notes";`
    );
  }
  if (stack.database !== 'none' && stack.api === 'trpc') {
    imports.push(`import * as notes from "./notes";`);
  }

  const lines = [
    ...imports,
    '',
    `const app = new Hono<{ Variables: { userId: string | null } }>();`,
    '',
    `app.use("*", cors({ origin: "${WEB_ORIGIN}", credentials: true }));`,
  ];

  if (stack.auth === 'clerk') {
    lines.push(`app.use("*", clerkMiddleware());`);
    lines.push(`app.use("*", async (c, next) => {`);
    lines.push(`  c.set("userId", getAuth(c)?.userId ?? null);`);
    lines.push(`  await next();`);
    lines.push(`});`);
  } else if (stack.auth === 'better-auth' && stack.database !== 'none') {
    lines.push(`app.use("*", async (c, next) => {`);
    lines.push(
      `  const session = await auth.api.getSession({ headers: c.req.raw.headers });`
    );
    lines.push(`  c.set("userId", session?.user.id ?? null);`);
    lines.push(`  await next();`);
    lines.push(`});`);
    lines.push(
      `app.on(["POST", "GET"], "/api/auth/*", (c) => auth.handler(c.req.raw));`
    );
  } else {
    lines.push(`app.use("*", async (c, next) => {`);
    lines.push(`  c.set("userId", null);`);
    lines.push(`  await next();`);
    lines.push(`});`);
  }

  lines.push('');
  lines.push(`app.get("/health", (c) => c.json({ ok: true }));`);

  if (stack.database !== 'none' && stack.api === 'none') {
    lines.push(restRoutes(stack.auth !== 'none'));
  }
  if (stack.database !== 'none' && stack.api === 'orpc') {
    lines.push(`const handler = new OpenAPIHandler(router);`);
    lines.push(`app.all("/api/*", async (c) => {`);
    lines.push(
      `  const { matched, response } = await handler.handle(c.req.raw, {`
    );
    lines.push(`    prefix: "/api",`);
    lines.push(
      `    context: { headers: c.req.raw.headers, userId: c.get("userId") },`
    );
    lines.push(`  });`);
    lines.push(`  if (matched) {`);
    lines.push(`    return c.newResponse(response.body, response);`);
    lines.push(`  }`);
    lines.push(`  return c.notFound();`);
    lines.push(`});`);
  }
  if (stack.database !== 'none' && stack.api === 'trpc') {
    lines.push(`app.use(`);
    lines.push(`  "/trpc/*",`);
    lines.push(`  trpcServer({`);
    lines.push(`    router: appRouter,`);
    lines.push(`    createContext: (_opts, c) => ({`);
    lines.push(`      userId: c.get("userId"),`);
    lines.push(`      notes: {`);
    lines.push(`        list: notes.listNotes,`);
    lines.push(`        create: notes.createNote,`);
    lines.push(`        update: notes.updateNote,`);
    lines.push(`        remove: notes.removeNote,`);
    lines.push(`      },`);
    lines.push(`    }),`);
    lines.push(`  }),`);
    lines.push(`);`);
  }

  lines.push('');
  lines.push(`serve({ fetch: app.fetch, port: 3333 });`);
  lines.push('');
  return lines.join('\n');
}

function restRoutes(authed: boolean): string {
  const deny = authed
    ? `  if (!c.get("userId")) {\n    return c.json({ error: "UNAUTHORIZED" }, 401);\n  }\n  `
    : '';
  return `
app.get("/notes", async (c) => {
  ${deny}return c.json(await listNotes(c.get("userId")));
});

app.post("/notes", async (c) => {
  ${deny}const body = await c.req.json<{ title: string; body: string }>();
  return c.json(await createNote(c.get("userId"), body));
});

app.patch("/notes/:id", async (c) => {
  ${deny}const body = await c.req.json<{ title: string; body: string }>();
  return c.json(await updateNote(c.get("userId"), { id: c.req.param("id"), ...body }));
});

app.delete("/notes/:id", async (c) => {
  ${deny}return c.json(await removeNote(c.get("userId"), c.req.param("id")));
});
`;
}

function emitWeb(ctx: EmitCtx, stack: HonoStack, dep: string): void {
  switch (stack.frontend) {
    case 'next':
      emitNextWeb(ctx, stack, dep);
      break;
    case 'tanstack-start':
      emitStartWeb(ctx, stack, dep);
      break;
    default: {
      const _exhaustive: never = stack.frontend;
      throw new Error(`unhandled frontend: ${_exhaustive}`);
    }
  }
}

function webDependencies(
  stack: HonoStack,
  dep: string
): Record<string, string> {
  const dependencies: Record<string, string> = {
    '@repo/ui': dep,
    react: '^19.1.1',
    'react-dom': '^19.1.1',
  };
  if (stack.auth === 'better-auth') {
    dependencies['better-auth'] = '^1.3.8';
  }
  if (stack.auth === 'clerk' && stack.frontend === 'next') {
    dependencies['@clerk/nextjs'] = '^6.31.5';
  }
  if (stack.auth === 'clerk' && stack.frontend === 'tanstack-start') {
    dependencies['@clerk/tanstack-react-start'] = '^0.25.0';
  }
  if (stack.database !== 'none' && stack.api === 'orpc') {
    dependencies['@orpc/client'] = 'beta';
    dependencies['@orpc/contract'] = 'beta';
    dependencies['@orpc/openapi'] = 'beta';
    dependencies['@repo/contract'] = dep;
    dependencies['@tanstack/react-query'] = '^5.89.0';
  }
  if (stack.database !== 'none' && stack.api === 'trpc') {
    dependencies['@repo/contract'] = dep;
    dependencies['@tanstack/react-query'] = '^5.89.0';
    dependencies['@trpc/client'] = '^11.5.1';
    dependencies['@trpc/react-query'] = '^11.5.1';
  }
  return dependencies;
}

function emitNextWeb(ctx: EmitCtx, stack: HonoStack, dep: string): void {
  const dependencies = {
    ...webDependencies(stack, dep),
    next: '^15.5.4',
  };
  setFile(
    ctx.files,
    'apps/web/package.json',
    JSON.stringify(
      {
        name: 'web',
        version: '0.0.0',
        private: true,
        type: 'module',
        scripts: {
          dev: 'next dev --port 3000',
          build: 'next build',
          start: 'next start',
        },
        dependencies,
        devDependencies: {
          '@repo/typescript-config': dep,
          '@tailwindcss/postcss': '^4.1.13',
          '@types/node': '^24.3.1',
          '@types/react': '^19.1.12',
          '@types/react-dom': '^19.1.9',
          tailwindcss: '^4.1.13',
          typescript: '^5.9.2',
        },
      },
      null,
      2
    )
  );
  setFile(
    ctx.files,
    'apps/web/tsconfig.json',
    JSON.stringify(
      {
        extends: '@repo/typescript-config/base.json',
        compilerOptions: {
          jsx: 'preserve',
          lib: ['DOM', 'DOM.Iterable', 'ES2022'],
          noEmit: true,
          paths: { '@/*': ['./*'] },
        },
        include: ['**/*.ts', '**/*.tsx', 'next-env.d.ts'],
      },
      null,
      2
    )
  );
  setFile(
    ctx.files,
    'apps/web/next.config.ts',
    `import type { NextConfig } from "next";

const nextConfig: NextConfig = {};

export default nextConfig;
`
  );
  setFile(
    ctx.files,
    'apps/web/postcss.config.mjs',
    `const config = {
  plugins: {
    "@tailwindcss/postcss": {},
  },
};

export default config;
`
  );
  setFile(
    ctx.files,
    'apps/web/next-env.d.ts',
    `/// <reference types="next" />
/// <reference types="next/image-types/global" />
`
  );
  setFile(
    ctx.files,
    'apps/web/app/globals.css',
    `@import "tailwindcss";
`
  );
  setFile(ctx.files, 'apps/web/app/providers.tsx', nextProviders(stack));
  setFile(
    ctx.files,
    'apps/web/app/layout.tsx',
    `import type { Metadata } from "next";
import { Providers } from "./providers";
import "./globals.css";

export const metadata: Metadata = { title: "${ctx.projectName}" };

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
`
  );
  setFile(
    ctx.files,
    'apps/web/app/page.tsx',
    `${stack.database !== 'none' ? `import Link from "next/link";\n\n` : ''}export default function HomePage() {
  return (
    <main className="mx-auto flex min-h-screen max-w-xl flex-col gap-4 p-8">
      <h1 className="text-2xl font-semibold">${ctx.projectName}</h1>
      ${
        stack.database !== 'none'
          ? `<p>
        <Link className="underline" href="/notes">
          Open notes
        </Link>
      </p>`
          : ''
      }
    </main>
  );
}
`
  );

  if (stack.auth === 'better-auth') {
    setFile(
      ctx.files,
      'apps/web/lib/auth-client.ts',
      `import { createAuthClient } from "better-auth/react";

export const authClient = createAuthClient({
  baseURL: process.env.NEXT_PUBLIC_SERVER_URL ?? "${SERVER_URL}",
});
`
    );
  }
  if (stack.database !== 'none' && stack.api === 'orpc') {
    setFile(
      ctx.files,
      'apps/web/lib/orpc-link.ts',
      `import { OpenAPILink } from "@orpc/openapi/fetch";
import { contract } from "@repo/contract";

export function createOrpcLink(getHeaders?: () => Promise<Record<string, string>>) {
  return new OpenAPILink(contract, {
    url: process.env.NEXT_PUBLIC_SERVER_URL ?? "${SERVER_URL}",
    fetch: (url, init) =>
      globalThis.fetch(url, {
        ...init,
        credentials: "include",
      }),
    ...(getHeaders ? { headers: getHeaders } : {}),
  });
}
`
    );
  }
  if (stack.database !== 'none' && stack.api === 'trpc') {
    setFile(
      ctx.files,
      'apps/web/lib/trpc.ts',
      `import { createTRPCReact } from "@trpc/react-query";
import type { AppRouter } from "@repo/contract";

export const trpc = createTRPCReact<AppRouter>();
`
    );
  }
  if (stack.database !== 'none') {
    setFile(
      ctx.files,
      'apps/web/app/notes/notes-client.tsx',
      nextNotesClient(stack)
    );
    setFile(
      ctx.files,
      'apps/web/app/notes/page.tsx',
      `import Link from "next/link";
import { NotesClient } from "./notes-client";

export default function NotesPage() {
  return (
    <main className="mx-auto flex min-h-screen max-w-xl flex-col gap-6 p-8">
      <h1 className="text-2xl font-semibold">Notes</h1>
      <Link className="text-sm underline" href="/">
        Home
      </Link>
      <NotesClient />
    </main>
  );
}
`
    );
  }
}

function nextProviders(stack: HonoStack): string {
  if (stack.auth === 'clerk') {
    return `"use client";

import { ClerkProvider } from "@clerk/nextjs";

export function Providers(props: { children: React.ReactNode }) {
  return <ClerkProvider>{props.children}</ClerkProvider>;
}
`;
  }
  return `export function Providers(props: { children: React.ReactNode }) {
  return props.children;
}
`;
}

function notesHttpPath(stack: HonoStack): string {
  if (stack.api === 'orpc') {
    return '/api/notes';
  }
  return '/notes';
}

function nextNotesClient(stack: HonoStack): string {
  if (stack.api === 'trpc') {
    return `"use client";

import { useState } from "react";
import { createTRPCProxyClient, httpBatchLink } from "@trpc/client";
import type { AppRouter } from "@repo/contract";
import { Button } from "@repo/ui/button";
import { Card } from "@repo/ui/card";
import { Input } from "@repo/ui/input";

const serverUrl = process.env.NEXT_PUBLIC_SERVER_URL ?? "${SERVER_URL}";
const client = createTRPCProxyClient<AppRouter>({
  links: [
    httpBatchLink({
      url: serverUrl + "/trpc",
      fetch: (url, init) => fetch(url, { ...init, credentials: "include" }),
    }),
  ],
});

type Note = { id: string; title: string; body: string };

export function NotesClient() {
  const [title, setTitle] = useState("");
  const [body, setBody] = useState("");
  const [notes, setNotes] = useState<Note[]>([]);

  return (
    <div className="flex flex-col gap-6">
      <form
        className="flex flex-col gap-3"
        onSubmit={(event) => {
          event.preventDefault();
          void client.notes.create.mutate({ title, body }).then(async () => {
            setTitle("");
            setBody("");
            setNotes(await client.notes.list.query());
          });
        }}
      >
        <Input name="title" placeholder="Title" value={title} onChange={(event) => setTitle(event.target.value)} required />
        <Input name="body" placeholder="Body" value={body} onChange={(event) => setBody(event.target.value)} />
        <Button type="submit">Add note</Button>
      </form>
      <ul className="flex flex-col gap-3">
        {notes.map((note) => (
          <li key={note.id}>
            <Card className="p-4">
              <h2 className="font-medium">{note.title}</h2>
              <p className="text-sm opacity-80">{note.body}</p>
            </Card>
          </li>
        ))}
      </ul>
    </div>
  );
}
`;
  }

  const path = notesHttpPath(stack);
  return `"use client";

import { useState } from "react";
import { Button } from "@repo/ui/button";
import { Card } from "@repo/ui/card";
import { Input } from "@repo/ui/input";

const serverUrl = process.env.NEXT_PUBLIC_SERVER_URL ?? "${SERVER_URL}";

type Note = { id: string; title: string; body: string };

export function NotesClient() {
  const [title, setTitle] = useState("");
  const [body, setBody] = useState("");
  const [notes, setNotes] = useState<Note[]>([]);

  return (
    <div className="flex flex-col gap-6">
      <form
        className="flex flex-col gap-3"
        onSubmit={(event) => {
          event.preventDefault();
          void fetch(serverUrl + "${path}", {
            method: "POST",
            credentials: "include",
            headers: { "content-type": "application/json" },
            body: JSON.stringify({ title, body }),
          }).then(async () => {
            setTitle("");
            setBody("");
            const response = await fetch(serverUrl + "${path}", { credentials: "include" });
            setNotes(await response.json());
          });
        }}
      >
        <Input name="title" placeholder="Title" value={title} onChange={(event) => setTitle(event.target.value)} required />
        <Input name="body" placeholder="Body" value={body} onChange={(event) => setBody(event.target.value)} />
        <Button type="submit">Add note</Button>
      </form>
      <ul className="flex flex-col gap-3">
        {notes.map((note) => (
          <li key={note.id}>
            <Card className="p-4">
              <h2 className="font-medium">{note.title}</h2>
              <p className="text-sm opacity-80">{note.body}</p>
            </Card>
          </li>
        ))}
      </ul>
    </div>
  );
}
`;
}

function emitStartWeb(ctx: EmitCtx, stack: HonoStack, dep: string): void {
  const dependencies = {
    ...webDependencies(stack, dep),
    '@tanstack/react-router': '^1.132.0',
    '@tanstack/react-router-devtools': '^1.132.0',
    '@tanstack/react-start': '^1.132.0',
  };
  setFile(
    ctx.files,
    'apps/web/package.json',
    JSON.stringify(
      {
        name: 'web',
        version: '0.0.0',
        private: true,
        type: 'module',
        scripts: {
          dev: 'vite dev',
          build: 'vite build',
          start: 'vite preview',
        },
        dependencies,
        devDependencies: {
          '@repo/typescript-config': dep,
          '@tailwindcss/vite': '^4.1.13',
          '@types/node': '^24.3.1',
          '@types/react': '^19.1.12',
          '@types/react-dom': '^19.1.9',
          '@vitejs/plugin-react': '^5.0.2',
          tailwindcss: '^4.1.13',
          typescript: '^5.9.2',
          vite: '^7.1.5',
          'vite-tsconfig-paths': '^5.1.4',
        },
      },
      null,
      2
    )
  );
  setFile(
    ctx.files,
    'apps/web/tsconfig.json',
    JSON.stringify(
      {
        extends: '@repo/typescript-config/base.json',
        compilerOptions: {
          lib: ['ES2022', 'DOM', 'DOM.Iterable'],
          jsx: 'react-jsx',
          noEmit: true,
          paths: { '@/*': ['./src/*'] },
        },
        include: ['src', 'vite.config.ts'],
      },
      null,
      2
    )
  );
  setFile(
    ctx.files,
    'apps/web/vite.config.ts',
    `import tailwindcss from "@tailwindcss/vite";
import { tanstackStart } from "@tanstack/react-start/plugin/vite";
import viteReact from "@vitejs/plugin-react";
import { defineConfig } from "vite";
import tsConfigPaths from "vite-tsconfig-paths";

export default defineConfig({
  server: {
    port: 3000,
  },
  plugins: [
    tsConfigPaths({ projects: ["./tsconfig.json"] }),
    tanstackStart(),
    viteReact(),
    tailwindcss(),
  ],
});
`
  );
  setFile(
    ctx.files,
    'apps/web/src/styles.css',
    `@import "tailwindcss";
`
  );
  setFile(
    ctx.files,
    'apps/web/src/components/providers.tsx',
    `import type { ReactNode } from "react";

export function Providers(props: { children: ReactNode }) {
  return props.children;
}
`
  );
  setFile(
    ctx.files,
    'apps/web/src/routes/__root.tsx',
    `import { HeadContent, Outlet, Scripts, createRootRoute } from "@tanstack/react-router";
import { TanStackRouterDevtools } from "@tanstack/react-router-devtools";
import appCss from "../styles.css?url";
import { Providers } from "../components/providers";

export const Route = createRootRoute({
  head: () => ({
    meta: [
      { charSet: "utf-8" },
      { name: "viewport", content: "width=device-width, initial-scale=1" },
      { title: "${ctx.projectName}" },
    ],
    links: [{ rel: "stylesheet", href: appCss }],
  }),
  component: RootDocument,
});

function RootDocument() {
  return (
    <html lang="en">
      <head>
        <HeadContent />
      </head>
      <body>
        <Providers>
          <Outlet />
        </Providers>
        <TanStackRouterDevtools />
        <Scripts />
      </body>
    </html>
  );
}
`
  );
  setFile(
    ctx.files,
    'apps/web/src/routes/index.tsx',
    `import { Link, createFileRoute } from "@tanstack/react-router";

export const Route = createFileRoute("/")({
  component: HomePage,
});

function HomePage() {
  return (
    <main className="mx-auto flex min-h-screen max-w-xl flex-col gap-4 p-8">
      <h1 className="text-2xl font-semibold">${ctx.projectName}</h1>
      ${
        stack.database !== 'none'
          ? `<p>
        <Link className="underline" to="/notes">
          Open notes
        </Link>
      </p>`
          : ''
      }
    </main>
  );
}
`
  );
  if (stack.auth === 'better-auth') {
    setFile(
      ctx.files,
      'apps/web/src/lib/auth-client.ts',
      `import { createAuthClient } from "better-auth/react";

export const authClient = createAuthClient({
  baseURL: import.meta.env.VITE_SERVER_URL ?? "${SERVER_URL}",
});
`
    );
  }
  if (stack.database !== 'none') {
    setFile(ctx.files, 'apps/web/src/routes/notes.tsx', startNotesRoute(stack));
  }
}

function startNotesRoute(stack: HonoStack): string {
  if (stack.api === 'trpc') {
    return `import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { createTRPCProxyClient, httpBatchLink } from "@trpc/client";
import type { AppRouter } from "@repo/contract";
import { Button } from "@repo/ui/button";
import { Input } from "@repo/ui/input";

const serverUrl = import.meta.env.VITE_SERVER_URL ?? "${SERVER_URL}";
const client = createTRPCProxyClient<AppRouter>({
  links: [
    httpBatchLink({
      url: serverUrl + "/trpc",
      fetch: (url, init) => fetch(url, { ...init, credentials: "include" }),
    }),
  ],
});

export const Route = createFileRoute("/notes")({
  component: NotesPage,
});

function NotesPage() {
  const [title, setTitle] = useState("");
  return (
    <main className="mx-auto flex min-h-screen max-w-xl flex-col gap-4 p-8">
      <h1 className="text-2xl font-semibold">Notes</h1>
      <form
        className="flex flex-col gap-3"
        onSubmit={(event) => {
          event.preventDefault();
          void client.notes.create.mutate({ title, body: "" });
        }}
      >
        <Input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Title" />
        <Button type="submit">Add note</Button>
      </form>
    </main>
  );
}
`;
  }

  return `import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { Button } from "@repo/ui/button";
import { Input } from "@repo/ui/input";

const serverUrl = import.meta.env.VITE_SERVER_URL ?? "${SERVER_URL}";

export const Route = createFileRoute("/notes")({
  component: NotesPage,
});

function NotesPage() {
  const [title, setTitle] = useState("");
  return (
    <main className="mx-auto flex min-h-screen max-w-xl flex-col gap-4 p-8">
      <h1 className="text-2xl font-semibold">Notes</h1>
      <form
        className="flex flex-col gap-3"
        onSubmit={(event) => {
          event.preventDefault();
          void fetch(serverUrl + "${notesHttpPath(stack)}", {
            method: "POST",
            credentials: "include",
            headers: { "content-type": "application/json" },
            body: JSON.stringify({ title, body: "" }),
          });
        }}
      >
        <Input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Title" />
        <Button type="submit">Add note</Button>
      </form>
    </main>
  );
}
`;
}
